name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: 1.82.0

    - name: Build
      run: cargo build --release --verbose

    - name: Create a GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/*

    - name: Upload release assets
      uses: actions/upload-artifact@v3
      with:
        name: release-assets
        path: target/release/*
